server:
  port: 80

eureka:
  client:
    #表示是否将自己注册进注册中心，默认为true
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。
    fetchRegistry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://localhost:7001/eureka
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000